services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: samsonm
      POSTGRES_PASSWORD: P@ssW0rd
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      # Port used for RabbitMQ API for message publishing and the UI Management
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    image: samsonmarikwa/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - zipkin

  apigw:
    image: samsonmarikwa/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    depends_on:
      - zipkin
      - eureka-server

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: