apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer
  ports:
    - port: 8080
      targetPort: 8080  # the port where the application is exposed. targetPort and containerPort must be identical.
      # Infact, containerPort definition may be skipped.
  type: LoadBalancer