server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    password: P@ssW0rd
    url: jdbc:postgresql://postgres:5432/customer
    username: samsonm
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
