server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    password: P@ssW0rd
    url: jdbc:postgresql://localhost:5432/customer
    username: samsonm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
