server:
  port: 8081

spring:
  application:
    name: fraud

  datasource:
    url: jdbc:postgresql://postgres:5432/fraud
    username: samsonm
    password: P@ssW0rd

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
