apiVersion: v1
kind: Service
metadata:
  name: fraud
spec:
  selector:
    app: fraud
  ports:
    - port: 80
      targetPort: 8081  # the port where the application is exposed. targetPort and containerPort must be identical.
                        # Infact, containerPort definition may be skipped.
  type: NodePort