server:
  port: 8300

spring:
  application:
    name: notification

  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: samsonm
    password: P@ssW0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


