server:
  port: 8300

spring:
  application:
    name: notification

  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: samsonm
    password: P@ssW0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#These are arbitrary keys used in the config class
rabbitmq:
#  exchange - Topic Exchange
  exchange:
    internal: internal.exchange
#  queue - identifies a queue attached to a consumer (microservice)
  queue:
    notification: notification.queue
# Used in a binding exchange and the queue
  routing-key:
    internal-notification: internal.notification.routing-key




